### ISSUE TITLE
Probably bug in afterFind() (not populated after find)

### ISSUE THREAD

**Issue by kwazar** [creocoder/yii2-taggable#14]
It seems to me that here should not be a negation:

     /**
     * @return void
     */
    public function afterFind()
    {
        if (!$this->owner->isRelationPopulated($this->tagRelation)) {
            return;
        }

        $this->populateTagNames();
    }

correct version, without negation in if statement:

     /**
     * @return void
     */
    public function afterFind()
    {
        if ($this->owner->isRelationPopulated($this->tagRelation)) {
            return;
        }

        $this->populateTagNames();
    }

or

    /**
     * @return void
     */
    public function afterFind()
    {
        if (!$this->owner->isRelationPopulated($this->tagRelation)) {
            $this->populateTagNames();
        }
    }

**Comment by creocoder** [comment]
Original code is **correct**. Anyway thanks for idea about slight refactoring. Code changed to:

```php
/**
 * @return void
 */
public function afterFind()
{
    if ($this->owner->isRelationPopulated($this->tagRelation)) {
        $this->populateTagNames();
    }
}
```

**Comment by kwazar** [comment]
Sorry for my english. It's really good job but i dont understand why not populated after that example:

$model = creocoder\taggable:findOne(id);

...it fired afterFind() but dont execute method populateTagNames() in that first time.

**Comment by creocoder** [comment]
@kwazar To not make potential excess query. For example:

```php
$model = Post::findOne(1); // nothing populated here
$model->tagNames; // tags populated

$models = Post::findAll([]); // nothing populated here

foreach ($models as $model) {
    echo $model->tagNames; // tags populated
}

$models = Post::find()->with('tags')->all(); // tags populated here

foreach ($models as $model) {
    echo $model->tagNames; // tags already populated, no queries
}
```

If short you control population by native eager loading mechanism. This allow to not detach behavior when its not needed.

**Comment by creocoder** [comment]
@kwazar If you do not use `with()` than lazy population mechanism works. Tags populated on first time when you call `tagNames` property. If you use `with()` thats mean eager loading and tags populated inside `afterFind()`. Everything simple.

**Comment by kwazar** [comment]
Thanks you for your explanation, now i understand ideas.
