### ISSUE TITLE
Choosing of package

### ISSUE THREAD

**Issue by antonkomarev** [creocoder/yii2-taggable#18]
Hello, Alexander.

I'm now choosing taggable system for a new one project.
What's the main difference between your package and [this one](https://github.com/2amigos/yii2-taggable-behavior)?
I saw that you are supporting both of them.

Thanks in advance.

**Comment by creocoder** [comment]
Sorry, I can not answer this question for reasons of ethics. Choose your own ;-)

**Comment by antonkomarev** [comment]
I'm keep using this one, just wanted to know the differences. Thank you.
Just waiting for the tags nesting to be implemented and that would be perfect choice for me :}
