### ISSUE TITLE
Overwrite afterSave()

### ISSUE THREAD

**Issue by gagiD** [creocoder/yii2-taggable#21]
Hi.

I have _afterSave()_ implemented in ActiveRecord which use **TaggableBehavior**.
And _afterSave()_ from **TaggableBehavior** dones't have any effect. When I comment my **TaggableBehavior** works normal.

Any fix for this?

**Comment by creocoder** [comment]
@gagiD 

> Any fix for this?

Do you have `parent::afterSave($insert, $changedAttributes)` at start of your overriden method?

**Comment by gagiD** [comment]
Thanks for answer :smile: 

Yes.

``` php
public function afterSave($insert) 
{
    $return = parent::beforeSave($insert);

    // ...

    return $return;
}
```

And I added **$changedAttributes** parameter but no difference.

**Comment by gagiD** [comment]
Oh, this is embarrassing :grimacing:

Sorry for interrupting.
